input_channels: 3
output_channels: 1

# binary_cross_entropy, negative_log_likelihood, mean_square_error, custom_mse
kind_loss: "binary_cross_entropy"
kind_optimizer: "Adam"
train_transform_variant: "threshold_mask"

path_checkpoint: '/mnt/beegfs/work/FoMo_AIISDH/scascianelli/2023_ICCV_bilama/checkpoints/'
learning_rate: 1.5e-4
threshold: 0.5


optimizer:
  betas: [ 0.9, 0.95 ]
  eps: 1.0e-08
  weight_decay: 0.05
  amsgrad: False


# LaMa Configuration
init_conv_kwargs:
  ratio_gin: 0
  ratio_gout: 0
down_sample_conv_kwargs:
  ratio_gin: 0
  ratio_gout: 0
resnet_conv_kwargs:
  ratio_gin: 0.75
  ratio_gout: 0.75


# Train configuration
train_patch_size: 256
train_log_every: 100
train_max_value: 500
train_kwargs:
  shuffle: True
  pin_memory: True


# Valid configuration
valid_patch_size: 256
valid_stride: 256
valid_kwargs:
  shuffle: False
  pin_memory: True


# Test configuration
test_batch_size: 1
test_patch_size: 256
test_stride: 256
test_kwargs:
  shuffle: False
  pin_memory: True
  batch_size: 1