client_config_backend: settings
client_config:
  client_id:      1080745903255-nd98ijc6o725qv61fq2lemfikpa7d57i.apps.googleusercontent.com
  client_secret: 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

save_credentials: True
save_credentials_backend: file
save_credentials_file: credentials.json

get_refresh_token: True

oauth_scope:
  - https://www.googleapis.com/auth/drive.file
  - https://www.googleapis.com/auth/drive.install